# deploy.yml
- name: Deploy Spring Boot App
  hosts: localhost
  become: false
  tasks:
    - name: Stop existing container (if running)
      shell: docker stop orders-app || true && docker rm orders-app || true

    - name: Run the new Docker container
      shell: docker run -d --name orders-app -p 8000:8000 orders-app
