# server:
#   port: 8000
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     driverClassName: org.h2.Driver
#     username: sa
#     password: ''
#   h2:
#     console:
#       enabled: true
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true
    
server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:file:/data/ordersdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never
